### PR TITLE
Add NUMBER and BOOLEAN tokens

### PR DESCRIPTION
**Pull request by bogdancondorachi**
Hey @brendt, I know you said in #96 that you don't plan on adding new tokens so this might be pointless.

But I'm still taking my shoot on implementing `NUMBER` and `BOOLEAN` tokens because:

- they are an important part of syntax highlighting and deserve their own tokens
- most themes handle them differently, making it impossible to highlight them correctly on multi-theme setup

If approved, I'm happy to do another PR on updating the themes/classes with these new tokens.

### CODE REVIEW

**Comment by brendt** [comment]
I'm fine merging this in, but we cannot update existing languages without it being a breaking change: if a specific word changes to use a new class while people don't have this CSS class present in their stylesheet, their highlighting will break. 

So I'm fine merging this in, and you can use it in newly added languages like #121, but we won't be able to update new languages until a later point.

We should also update `LightTerminalTheme` to include these changes, can you add those changes to this PR as well?

**Comment by brendt** [comment]
Thanks!

**Comment by brendt** [comment]
Tagged: https://github.com/tempestphp/highlight/releases/tag/2.5.0

**Comment by bogdancondorachi** [comment]
@brendt I've updated the `LightTerminalTheme` with the added tokens.

> So I'm fine merging this in, and you can use it in newly added languages like https://github.com/tempestphp/highlight/pull/121, but we won't be able to update new languages until a later point.

Now this is perfectly fine for me, though I believe it's not really a breaking change if we are to update current languages to include these tokens as well as it all depends on the user CSS, basically if token CSS is missing it would simply not add the respective color, leaving it with a blank class if I'm correct. I see it more as a missing feature if they don't update their CSS.

Steps I'm seeing are as follows:
- Update themes at first (some also needs color correction)
- Update languages where necessary

You can ping me on Discord to discuss more on this if you want. :)

**Comment by brendt** [comment]
Tagged: https://github.com/tempestphp/highlight/releases/tag/2.6.0

**Pull request merged**
