### PR TITLE
Add Antlers support

### PR DESCRIPTION
**Pull request by SRWieZ**
Hi Brendt! Love your work with console and highlight

Here is my contribution to support [Antlers](https://statamic.dev/antlers) template language of Statamic.

It was pretty fun to code.
I like that way we can write tests in attributes.
I reused some Patterns from Xml and PHP, hope it's ok.

I noticed that there is no CSS for operators, is that a bug ?

### ❓Need help on one edge case
I tried several things to fix this bug without success. Is there a way to prevent injection into another injection ?
One thing I didn't tried is to put `#[After]` on `AntlersCommentInjection` and remove other injections from `$content`, is this the way ?

image

### 📋 Before merging
- [ ] Fix antlers comments having antlers tags being highlighted 
- [x] Write more tests
- [x] If #123 passes there is a little changes to make

Until you have time to review, here is a little preview 😃

### 🏞️ Preview
http://localhost:8080/?target=targets/antlers.md

image

### CODE REVIEW

**Comment by brendt** [comment]
> Need help on one edge case

This happens because of how patterns and injections are parsed, the problem actually isn't in the comment injection or pattern, it's in `AntlersTagLanguage`. Because this is a sub-language, it doesn't know about its scope. Normally, the highlighter will make sure that no tokens can live within a block that's already a comment, but because `AntlersTagLanguage` is injected, it negates all those checks.

The solution would be to keep the comment pattern and all patterns related to `AntlersTagLanguage` together in one language. My proposal would be to have `AntlersLanguage`, and ditch `AntlersTagLanguage`. That means you can also ditch `AntlersCommentLanguage`, since it's already covered with the `CommentPattern`. The only two injections you'll need to keep are `AntlersEchoInjection` and `AntlersPhpInjection`, since those two are actually injecting separate languages. 

> I noticed that there is no CSS for operators, is that a bug ?

I actually plan on merging #123 soon, so I guess you'll want to wait and apply patterns for those newly added tokens as well?

Let me know if you need more help! You can also join our [Discord](https://discord.gg/pPhpTGUMPQ) to talk in real time :)

**Comment by brendt** [comment]
FYI https://github.com/tempestphp/highlight/pull/123 has been merged :)

**Comment by SRWieZ** [comment]
Thanks for your answers!

I'm already on the discord but I'm only opening Discord when someone needs me there.

I will join the vocal channel when I reopen this PR. It may be only next week thought. 

Should I convert it as draft in the meantime ?

**Comment by brendt** [comment]
Yes it ca be draft :)

**Comment by brendt** [comment]
> Also, I feel like I've done something wrong by rebasing the PR. I would reopen a new PR if needed.

Makes sense 👍

> I tried with the suggested approach and resolved the comment issue but this came with a lot more complexity.

Gotcha. Blade is different in that most tags are written with `@` and not between `{{` brackets. Are you sure you can't write this:

```
{{(?:(?!{{|}}).)*?(?<match>{$quoted})(?:(?!{{|}}).)*?}}
```

As something more like this?

```
{{\s*(?<match>{$quoted})(?:(?!{{|}}).)\s*}}
```

**Comment by SRWieZ** [comment]
Unfortunately not, it's slightly worse.

This $quoted example is to match Operators like "=>" so it will need to catch more than whitespace and in this example, it will only match the second tag because it will only see this example as one tag:
`{{ ab => cd }} should only match last tag => {{ c=>d }}`

And it doesn't help my second point that is my biggest concern.

Here is my current regex and where it fails: https://regex101.com/r/gMpPJU/1

I want it to match every "=>" on those lines
```blade
{{ if a => b && c => d }} 
{{ {if a => b} && {c => d}  }}
```

I can write all the failing tests and maybe you can help me TDD this 😄

The more I think about it, the more I think it has to be a sub language because I don't think we can do a recursive pattern in PHP PCRE without doing 2 successive preg_match_all

**Comment by brendt** [comment]
> The more I think about it, the more I think it has to be a sub language because I don't think we can do a recursive pattern in PHP PCRE without doing 2 successive preg_match_all

Yeah you're probably right… but then we're stuck with the comments. However, we could fix comments like this:

- match everything between `{{` and `}}` as a separate Antlers sub language — name tbd
- Comments will be matched as well `# comment #`, we can write a pattern for this within that sub language

I think that should fix all problems. 

Sorry for going back and forth on this, it's definitely one of the more difficult languages to parse solely with regex…

**Comment by SRWieZ** [comment]
No worries, I knew from the beginning that it was not an easy one 😄

So I go back to injecting AntlersTagLanguage() next to AntlersPhpInjection() and AntlersEchoInjection(), but this time comment pattern should be in the sub language?

https://github.com/tempestphp/highlight/pull/124/commits/749bc421e8ec7b5adbf170db021db47c37485432#diff-e3e4595857edce00b02aa748801fcc680a123f0c105c0be5dd4d182b3f7f5469

Funny thing: Statamic was parsing Antlers with Regex in version 3, deprecated in version 4, recently removed in version 5. I'm sure it's for entirely different reasons, but worth noting.

**Comment by brendt** [comment]
Does the refactor work?

**Comment by SRWieZ** [comment]
Sorry didn't do any changes, I referenced an old commit. It was working, except the comment thing.

**Comment by SRWieZ** [comment]
Ok I went back to the first version with the suggested changes.
It works very well and is much more readable and efficient, except for the comments.

The current version renders like this, which I find even uglier:
Capture d’écran 2024-06-02 à 00 37 43

The first version was better I think.
This example of the comment embedding a tag should not happen often.

I spent way too many hours on this, going in circles. I give up here. 😅 
I made one last effort writing lots of tests to help anyone who would like to take over. Including two failing tests.

**Comment by brendt** [comment]
I'll try to work on this next week and see what I can come up with :)

**Comment by brendt** [comment]
Currently not gonna work on this, but might revisit later

**Pull request closed without merging**
